### ISSUE TITLE
Documentation Request for Global $datastore

### ISSUE THREAD

**Issue by FeralCatColonist** [Esri/arcade-expressions#41]
I'm in the process of making attribute rules on my enterprise geodatabase and wanted to know more about utilizing $datastore for filling in data derived from other feature classes. Based on previous experience using Arcade for field calculations, I understand that the $datastore global only accesses feature classes within the container of the current feature. Is this a correct understanding?

I have not seen this information explicitly spelled out; and am unsure what the behavior would be between feature datasets as well. These are the only links that I've seen with definitions for the $datastore.

https://developers.arcgis.com/arcade/guide/types/#featuresetcollection
https://developers.arcgis.com/arcade/guide/release-notes/#featureset-support-in-popups-and-attribute-rules

Are there other resources for understanding the behavior of $datastore better, if it does not exist currently, can the Dev  Team enhance its documentation?

**Comment by hhkaos** [comment]
Sorry @FeralCatColonist, I just noticed this question was never answered. This question is for the [ArcGIS Pro](https://community.esri.com/t5/arcgis-pro-questions/bd-p/arcgis-pro-questions) or [ArcGIS Pro SDK](https://community.esri.com/t5/arcgis-pro-sdk-questions/bd-p/arcgis-pro-sdk-questions) communitoes as this is a repo dedicated only to sharing expression templates.

In order to get your feedback to the right people about the documentation, I highly encourage you to use the feedback widget within the developer site:

![2023-10-17_13-19-21](https://github.com/Esri/arcade-expressions/assets/826965/7db6ccac-2494-44e5-874a-7e9b484a81e6)
